In [2]:
import numpy as np

In [9]:
a=np.array([[1,2,3],[4,5,6]]) # two dimension array 
a
print(*a)

[1 2 3] [4 5 6]


In [19]:
a= np.array([1,2,3,4,5,6], ndmin=3)# displayed as 3dimension array with the   ndmin( in how many dimensions for ) 
a

array([[[1, 2, 3, 4, 5, 6]]])

In [21]:
#data type parameter 
a= np.array([1,2,3], dtype=complex)
a


array([1.+0.j, 2.+0.j, 3.+0.j])

In [24]:
# data types in numpy 
# numpy supports many data types more than python

dt=np.dtype(np.int32)
dt

dtype('int32')

In [31]:
#int 8 , int16, int32 , int64 are equivalent to i1,i2,i3


dt=np.dtype('i8')
dt

dtype('int64')

In [34]:
# using endian notation 

dt=np.dtype('>i4')
dt

dtype('>i4')

In [38]:
dt=np.dtype([('age',np.int64)])
print(dt)


[('age', '<i8')]


In [40]:
#ndarray shape
a= np.array([[1,2,3],[3,4,5]])
a.shape# shows in rows and columns 



(2, 3)

In [50]:
#re shape  the array 
# you can only change from rows to columns , ex  (2,3) can be changed to (3,2)
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
# arange & ndim(no of dimensions) attributes

a= np.arange(24)
a.ndim

1

In [61]:
# reshaping the array (noof rows, noof columns , no of dimensions) 
#easy way to do it is ex for 24 , 12*2 or 4*6 or 2*2*6

a.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
w